### ISSUE TITLE
[FEAT] 체중 기록

### ISSUE THREAD

**Issue by gyulls2** [gyulls2/gyull-app#12]
## 📝 Description
메인 페이지에서 체중을 기록합니다.

## ✔️ TODO
- [x] 체중 기록 기능
- [x] 체중 수정 기능
- [x] 상태에 따라 버튼 '기록하기', '수정하기' 변경
- [x] 처음 입력한 체중과 비교값 계산해서 보여주기
- [x] BMI 계산

## 📌 ETC
기타 참고사항을 적어주세요.
