### ISSUE TITLE
[FEAT] 메인 페이지 데이터 패치 기능

### ISSUE THREAD

**Issue by gyulls2** [gyulls2/gyull-app#6]
## 📝 Description
메인 페이지에서 DB에서 필요한 정보를 받아와 보여줍니다.

## ✔️ TODO
- [x]  메인페이지 데이터 구조
- [x]  DB 목업데이터 세팅
- [x]  메인페이지 데이터 패치 기능 구현
    - [x]  zustand - 목표 칼로리, 목표 탄단지, 유저명
    - [x]  체중
    - 계산 로직 필요
    - [x]  끼니별 총 칼로리
    - [x]  총 칼로리
    - [x]  총 탄단지
- [x]  체중 확인 기능

## 📌 ETC
기타 참고사항을 적어주세요.
